image: docker:git
services:
- docker:dind

stages:
- test

test-image:
  stage: test
  script:
    - make
    - make -C tests
    - ./tests/run.sh ./tests/bin/test0
    - ./tests/run.sh ./tests/bin/test1
    - ./tests/run.sh ./tests/bin/test2
    - ./tests/run.sh ./tests/bin/test3
    - ./tests/run.sh ./tests/bin/test3+
    - ./tests/run.sh ./tests/bin/test4
    - ./tests/run.sh ./tests/bin/test5
  tags:
    - Atomos
  only:
    - master
